branches:
  - master
  - auto
  - try

container:
  image: registry.fedoraproject.org/fedora:26

context: 'f26-build-check'
required: true

# Build with deps
build: true
packages:
    - make
    - automake
    - gcc
    - go-md2man
    - libyaml-devel
    - glib2-devel
    - json-glib-devel
    - autoconf

# And call into automake
tests:
    - make check

artifacts:
    - test-suite.log

