branches:
  - master
  - auto
  - try

container:
  image: registry.fedoraproject.org/fedora:26

context: 'f26-build-check'
required: true

packages:
    - python3-pytoml
    - python3-PyYAML
    - make
    - golang-github-cpuguy83-go-md2man
    - bats

tests:
    - make install DESTDIR=/
    - make test

artifacts:
    - test-suite.log

